### ISSUE TITLE
SPI

### ISSUE THREAD

**Issue by LostStudent** [leomil72/tiny#2]
Does the Core include SPI.h?

Im trying to compile a RadioHead sketch to a ATTiny85 and getting: 
....
 fatal error: SPI.h: No such file or directory
 #include <SPI.h>
compilation terminated.
exit status 1
Error compiling for board ATtiny25/45/85.

**Comment by leomil72** [comment]
The ATtint85 core doesn’t have the SPI library for space reasons. Instead it uses a simplified version called tinySPI. You can include it in your sketch by adding #include <tinySPI.h> at the beginning of the code.
